# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
                ('accepted_on', models.DateTimeField(default=None)),
                ('accepted_by', models.IntegerField(default=None)),
                ('notes', models.TextField()),
                ('active', models.BooleanField(help_text='Check this box to set the is note active, to deactivate it please un check this box.')),
            ],
            options={
                'db_table': 'user_agreements',
            },
        ),
    ]
