# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useragreement',
            name='accepted_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='useragreement',
            name='accepted_on',
            field=models.DateTimeField(null=True),
        ),
    ]
